keys:
  - &admin age1xp3zdc7yl4c4pkar0sjchmr89v4sw4y32uflqm5t67rgm4kh8snqe3edxr
creation_rules:
  - path_regex: user.yaml$
    encrypted_regex: "-(password|token)$"
    key_groups:
      - age:
          - *admin
